### ISSUE TITLE
Frequent random dropouts when using Garmin Pilot

### ISSUE THREAD

**Issue by gazcorbe** [nguyenquyhy/Flight-Events#49]
Hi
Firstly, thanks for this great app.
However, I'm getting frequent dropouts (I hear a PC bing bong) when using garmin pilot and won't reconnect until go back flight-events
Sometimes i can just untick and tick the broadcast,
Sometimes I have to stop and start the tracking,
Sometimes I have to restart the whole app to get garmin pilot to reconnect.
Don't know if it's my computer of garmin pilot related or my PC
Here is a snippet from my log file:
2022-09-14 20:02:34.734 +01:00 [ERR] Cannot send network package!
System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at FlightEvents.Client.Logics.UdpBroadcastLogic.<>c__DisplayClass14_0.<<SendGpsAsync>b__0>d.MoveNext() in D:\a\Flight-Events\Flight-Events\FlightEvents.Client.Logics\UdpBroadcastLogic.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at FlightEvents.Client.Logics.ThrottleExecutor.ExecuteAsync(Func`1 action) in D:\a\Flight-Events\Flight-Events\FlightEvents.Client.Logics\DiscordRichPresentLogic.cs:line 248
   at FlightEvents.Client.Logics.UdpBroadcastLogic.SendGpsAsync(AircraftStatus status) in D:\a\Flight-Events\Flight-Events\FlightEvents.Client.Logics\UdpBroadcastLogic.cs:line 108
   at FlightEvents.Client.MainWindow.FlightConnector_AircraftStatusUpdated(Object sender, AircraftStatusUpdatedEventArgs e) in D:\a\Flight-Events\Flight-Events\FlightEvents.Client\MainWindow.xaml.cs:line 607

**Comment by gazcorbe** [comment]
moved flight events software to C drive and no issues today

**Comment by nguyenquyhy** [comment]
That's strange 😄.
